### ISSUE TITLE
"Toggle Earned" button is missing?

### ISSUE THREAD

**Issue by GIONAScm2** [Barokai/psnprofiles-enhanced#2]
When I view a PSNP trophy guide, the button to toggle earned trophies no longer appears for me. (Usually appears right beside the "hours to plat").

**Comment by Barokai** [comment]
thanks for the information, fixed with version 0.84 - you can force update it via tampermonkey or greasemonkey, or wait until it updates automatically.

keep in mind, that the button won't show if you don't have any earned trophies for a game when you view its guide.
